FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY apps/frontend ./apps/frontend
RUN cd apps/frontend && npm install
WORKDIR /app/apps/frontend
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]
