FROM node:20-alpine AS base
WORKDIR /app
COPY package.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages
RUN npm install
RUN npm run typecheck
WORKDIR /app/apps/api
CMD ["npm", "run", "dev"]
